version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/rootroot
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j-net
    restart: unless-stopped

networks:
  neo4j-net:

volumes:
  neo4j_data:
